### ISSUE TITLE
Minor: missing dependencies when installed via Pip

### ISSUE THREAD

**Issue by johnjreiser** [raffaem/pdfsak#17]
After installing pdfsak 1.3.3 via Pip, there are two missing dependencies: `tdqm` & `natsort`

Exact command line you used:
```
$ pdfsak
Traceback (most recent call last):
  File "/home/jreiser/.venv/bin/pdfsak", line 20, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

## installed tqdm via pip

$ pdfsak
Traceback (most recent call last):
  File "/home/jreiser/.venv/bin/pdfsak", line 23, in <module>
    from natsort import natsorted
ModuleNotFoundError: No module named 'natsort'
````

To quickly remedy existing 1.3.3:
```
pip3 install tqdm natsort
```

**Comment by raffaem** [comment]
Should be fixed in 1.3.4. Thanks!
